### ISSUE TITLE
Suggested Documention Changes

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#19]
My $02 cents worth

1. SIO Command $63 TCP Connect
What happens if it cannot connect?
If an error is returned, what is it?

2. SIO Command $64 TCP Disconnect
Do you get an error if you disconnect something that is not connected?
If so, what?

3. SIO Command $D2 UDP Read
"AUX1/AUX2 form a 16-bit value specifying length, which, for practical purposes of routable traffic, **should not exceed 512 bytes**."
AUX1/AUX2 form a 16-bit value specifying length, which, for practical purposes of routable traffic, **cannot exceed 512 bytes**.

4. SIO Command $D4 UDP Connect
"Buffer containing hostname as NUL terminated string"
Buffer containing hostname as **NULL** terminated string

5. SIO Command $F3 TNFS Save Host Slots
"Pointer to 256 byte character buffer containing 8 NUL terminated entries of 32 characters."
Pointer to 256 byte character buffer containing 8 **NULL** terminated entries of 32 characters.

6. SIO Command $F4 TNFS Read Host Slots
The hosts have no terminator, or is there a NULL terminating each entry?

**Comment by tschak909** [comment]
Awesome thanks, I will adjust each of these.

1. If a TCP connection fails, an error 144 will result (due to an E being
returned), as a 138 would indicate the fujinet itself is not sending back
an ACK or a NAK.
2. No, you don't. This command has no data frame.
3. agree on cannot.
4. agree on NULL
5. agree on NULL
6. NULL terminating each entry.

Thanks! :)

-Thom
