### ISSUE TITLE
Short key press detection is broken

### ISSUE THREAD

**Issue by TheMontezuma** [FujiNetWIFI/fujinet-platformio#362]
Short key press detection ( tested with button A ) is broken.  One can easily test it even without connecting to ATARI.

**Comment by mozzwald** [comment]
Current timeout for SHORTPRESS is 300ms which feels too long for a normal button press. Setting it to ~160ms feels good for me https://github.com/FujiNetWIFI/fujinet-platformio/blob/master/lib/hardware/keys.cpp#L11

@kaelef doing the above makes it harder to get a good double tap since you need to press and release before 160ms to register for double tap. Is it possible to change the logic and make the double tap work better? Maybe wait until TAP_MAXTIME to decide if we had single or double tap?

**Comment by kaelef** [comment]
Rewrote the key handling logic to make it easier to enter a short keypress
