### ISSUE TITLE
Enhancement: Reset

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#384]
With The!Cart, when you press the reset button on the cartridge, the next reset on the keyboard brings you the to Cartridge menu
It would be nice if pressing the reset button on FujiNet, the next reset would bring you to FujiNet menu instead of requiring a power cycle.

**Comment by tschak909** [comment]
I have thought about this, repeatedly. Trying to find ANY way to do this on the device.

The reason it works on the cartridge devices is because the cart slot has access to enough bus signals to force a system reset.

We don't have a reset signal on the SIO bus. (although one was planned to be added to what would become the 1200XL, it was deleted early in the planning stage.)

I've done two things to deal with this, as best as I can:

* use FRESET to reset the FujiNet. The next cold start then goes into CONFIG.
* jump to address $E477 to do a cold start, e.g. M E477 in DOS 2/MyDOS, or RUN E477 in OS/A+, DOS XL, SpartaDOS, XDOS, etc.

(another variation of this while e.g. in BASIC or cart is to POKE 580,1, and then X=USR(58487))

The Ultimate 1MB adds a cold start keypress capability, where holding down SELECT while pressing RESET guarantees a cold start.

-Thom
